/// Flutter icons GameIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GameIcons
///      fonts:
///       - asset: fonts/GameIcons.ttf
///
///
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class GameIcons {
  GameIcons._();

  static const _kFontFam = 'GameIcons';
  static const String? _kFontPkg = null;

  static const IconData broadsword =
      IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burning_meteor =
      IconData(0xe951, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chicken_leg =
      IconData(0xe964, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloak_and_dagger =
      IconData(0xe968, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossbow =
      IconData(0xe978, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossed_swords =
      IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData explosive_materials =
      IconData(0xe9b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grenade =
      IconData(0xe9e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hearts =
      IconData(0xe9fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helmet =
      IconData(0xe9fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horseshoe =
      IconData(0xea06, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData queen_crown =
      IconData(0xea74, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData round_bottom_flask =
      IconData(0xea86, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spear_head =
      IconData(0xeaac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tower =
      IconData(0xead2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bomb =
      IconData(0xf1e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horse_head =
      IconData(0xf7ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
